---
title: "final_project"
author: "Storm Zierden!"
format: gfm
editor: source
execute: 
  echo: false
  warning: false
  message: false
  
---

```{r}
#| label: setup

library(tidyverse)
library("sf")
library("tigris")
library(tidyr)
```

```{r}
#| label: data
redlegged <-read_csv("data-bad/redlegged-original/observations-714460.csv")

bullfrog <- read_csv("data-bad/bullfrog-original/observations-714470.csv")
```
```{r}
#| label: shapefile

counties_sf <- counties(cb = TRUE, class = "sf", year = 2022)

```



```{r}
#| label: clean-redleg

cleanred <- redlegged |>
  select(c(id, observed_on, quality_grade, place_guess, latitude, longitude, species_guess, scientific_name, common_name)) |>
  drop_na() |>
filter(place_guess != "Ensenada, MX-BN, MX") |>
  separate_wider_delim(observed_on, delim = "-", names = c("year", "month", "day"))|>
st_as_sf(coords = c("longitude", "latitude"), crs = 4269) |>
   st_join(counties_sf, join = st_nearest_feature) |>
st_drop_geometry()

```
#https://copilot.microsoft.com/shares/KLbgNqjQ2ykxWrLaikS7E

```{r}
#| label: clean-bullfrog

cleanbull <- bullfrog |>
   select(c(id, observed_on, quality_grade, latitude, longitude, species_guess, scientific_name, common_name)) |>
  drop_na() |>
  separate_wider_delim(observed_on, delim = "-", names = c("year", "month", "day"), )|>
  st_as_sf(coords = c("longitude", "latitude"), crs = 4269) |>
  st_join(counties_sf, join = st_intersects) |>
  st_drop_geometry() 

  
```

```{r}
#| label: counts_red

 red_count <- cleanred|>
  count(NAME, year) |>
  group_by(NAME) |>
  filter(n >= 5) |>
  filter(n_distinct(year) > 5) |>
  filter(year < '2026')
  
  bull_count <- cleanbull|>
  count(NAME, year) |>
  group_by(NAME) |>
  filter(n >= 5) |>
  filter(n_distinct(year) > 5) |>
  filter(year < '2026')
```

```{r}
#| label: join

frogs <- bull_count |>
  inner_join(red_count, by = c("NAME", "year")) |>
  replace_na(list(n.x = 0,
               n.y = 0)) |>
  rename(bullfrog = n.x,
              redfrog = n.y) |>
  group_by(year) |>
  summarise(
  Bullfrog = sum(bullfrog),
  Redfrog =sum(redfrog)
  ) |>
  pivot_longer(
    cols = c(Bullfrog, Redfrog),
    names_to = "Species",
    values_to = "count"
  ) 
  
```

```{r}
#| label: redfrog_viz
red_count|>
  ggplot(aes(x = as.numeric(year), y = n, group = NAME, color = NAME)) +
  geom_line() +
  geom_point() + 
  theme_light() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(x = "Year", 
       y = "Number of Frogs", 
       title = "Yearly Growth of California's Red-Legged Frog within Each County")

red_count|>
  ggplot(aes(x = as.numeric(year), y = n, group = NAME, color = NAME)) +
  geom_line() +
  geom_point() + 
  facet_wrap("NAME") +
  theme_light() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(x = "Year", 
       y = "Number of Frogs", 
       title = "Yearly Growth of California's Red-Legged Frog within Each County")
  
```


```{r}
#|  label: comparison_viz

frogs |>
  ggplot(aes(x = year, y = count, fill = Species)) +
  geom_col(position = "dodge") +
  scale_fill_manual(
    values = c(
      Bullfrog = "#556b2f",
      Redfrog  = "#AA2704"
    )
  ) +
  labs(
    x = "Year",
    y = "Total Number of Frogs",
    title = "California Red-Legged Frog vs American Bullfrog Population in California Over Time"
  ) +
  theme_light(base_size = 14)
```

